merge to main
CU-Robotics/firmware pull request #12
Opened 2023-10-25 02:32 UTC by Pandabear1125

yay

2023-10-25 02:44 UTC, StudentKyle requested changes
See code notes

2023-10-25 02:44 UTC, StudentKyle commented on src/sensors/dr16.hpp
> +    float get_r_switch();
You have undocumented members

2023-10-25 02:44 UTC, StudentKyle commented on src/sensors/dr16.hpp
> +	void Init();
Should these functions be capitalized?

2023-10-25 02:44 UTC, StudentKyle commented on src/sensors/dr16.hpp
> +	void Read();
Capitalization?

2023-10-25 03:11 UTC, StudentKyle commented
Changes fixed above comments, looks good!

2023-10-25 03:11 UTC, Pandabear1125 commented
Need to add timeout for invalid data to write 0s.

2023-10-28 06:33 UTC, Pandabear1125 commented
Ready to merge, but see issue #13 for future changes

2023-10-28 22:56 UTC, StudentKyle approved these changes
Looks good!

2023-10-28 22:58 UTC, merged