Merge makefile
CU-Robotics/firmware pull request #22
Opened 2023-12-18 02:00 UTC by Pandabear1125

2023-12-18 16:29 UTC, Pandabear1125 commented
Makefile is functional (and easy to use), ready to be used :)

2023-12-18 16:51 UTC, StudentKyle requested changes
Add .DS_Store to gitignore

2023-12-18 16:51 UTC, StudentKyle commented on libraries/Adafruit_ICM20X/.DS_Store
.DS_Store is a MacOS file structure thing that isn't needed. We should probably remove it, likely by adding it to the gitignore (there are .DS_Store files elsewhere as well)

2023-12-19 05:53 UTC, Rishi-H approved these changes
Looks good to me. Thanks for spending the time to do this.

2023-12-19 05:53 UTC, merged

2023-12-19 06:06 UTC, Pandabear1125 commented
Keeping branch open in case makefile requires revision.