Merging CAN to main
CU-Robotics/firmware pull request #5
Opened 2023-10-14 22:34 UTC by Pandabear1125

2023-10-15 00:50 UTC, StudentKyle commented
Closing and opening to run doxygen test

2023-10-21 22:50 UTC, StudentKyle commented
re-running test

2023-10-21 22:57 UTC, StudentKyle commented
It looks like there are so many errors that the comment bot fails.

2023-10-25 01:14 UTC, StudentKyle commented
Documentation looks good

2023-10-25 01:15 UTC, StudentKyle requested changes
Documentation looks good, but file structure is not correct with how the rest of the project is set up.

2023-10-25 01:22 UTC, StudentKyle commented on src/comms/rm_CAN.hpp
> +  /// @param value A value in the range of []
Incomplete docs

2023-10-25 02:26 UTC, Rishi-H approved these changes

2023-10-25 02:26 UTC, StudentKyle approved these changes
Looks good

2023-10-25 02:28 UTC, merged